# permissions for end users to view inheritors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inheritor-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: label-inheritance-operator
    app.kubernetes.io/part-of: label-inheritance-operator
    app.kubernetes.io/managed-by: kustomize
  name: inheritor-viewer-role
rules:
- apiGroups:
  - labels.theisferre
  resources:
  - inheritors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - labels.theisferre
  resources:
  - inheritors/status
  verbs:
  - get
